### ISSUE TITLE
nsenter: failed to unshare namespaces: Invalid argument

### ISSUE THREAD

**Issue by cmoulliard** [genuinetools/img#143] opened 2018-07-17 12:58 UTC
I get this error when I issue the command to start the `img` container on macos

```
docker run --rm -it -w /home/user/src -v "/$(pwd)/spring-boot:/home/user/src:ro" -v "/$HOME/.docker:/root/.docker:ro" --name img --cap-addSETGID --cap-add SETUID --security-opt apparmor=unconfined --security-opt seccomp=unconfined r.j3ss.co/img build -t user/myimage .
nsenter: failed to unshare namespaces: Invalid argument
```

Docker info

```
Containers: 50
 Running: 11
 Paused: 0
 Stopped: 39
Images: 131
Server Version: 1.13.1
Storage Driver: overlay2
 Backing Filesystem: xfs
 Supports d_type: true
 Native Overlay Diff: true
Logging Driver: journald
Cgroup Driver: systemd
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
 Log: 
Swarm: inactive
Runtimes: docker-runc runc
Default Runtime: docker-runc
Init Binary: docker-init
containerd version:  (expected: aa8187dbd3b7ad67d8e5e3a15115d3eef43a7ed1)
runc version: N/A (expected: 9df8b306d01f59d3a8029be411de015b7304dd8f)
init version: N/A (expected: 949e6facb77383876aeff8a6944dde66b3089574)
Security Options:
 seccomp
  Profile: default
 selinux
Kernel Version: 3.10.0-693.21.1.el7.x86_64
Operating System: CentOS Linux 7 (Core)
OSType: linux
Architecture: x86_64
CPUs: 2
Total Memory: 1.954GiB
Name: minishift
ID: PWZQ:O5OI:AMTH:2IVK:E3FW:IX2G:BJ6X:JTWS:MW2N:YCY3:BDUI:LFAZ
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Labels:
 provider=xhyve
Experimental: false
Insecure Registries:
 172.30.0.0/16
 127.0.0.0/8
Live Restore Enabled: false
```

**Comment by jessfraz** [comment] 2018-07-17 13:00
If you have docker on a Mac you don't need this this isn't intended to work

**Comment by jessfraz** [comment] 2018-07-17 13:01
Duplicate of https://github.com/genuinetools/img/issues/44

**Closed by jessfraz** 2018-07-17 13:00 UTC

**Comment by zunkree** [comment] 2018-09-13 14:18
Have the same issue with kubernetes and containerd when run `img build` in privileged container under non root user. Kubernetes version is 1.10.6, containerd version is 1.1.2.
