### ISSUE TITLE
COPY --from fails

### ISSUE THREAD

**Issue by pixelspark** [genuinetools/img#130] opened 2018-06-21 07:13 UTC
Dockerfile (up to the line that fails):
````
FROM php:7.0-apache

# Set correct document root
ENV APACHE_DOCUMENT_ROOT /var/www/webroot
RUN sed -ri -e 's!/var/www/html!${APACHE_DOCUMENT_ROOT}!g' /etc/apache2/sites-available/*.conf
RUN sed -ri -e 's!/var/www/!${APACHE_DOCUMENT_ROOT}!g' /etc/apache2/apache2.conf /etc/apache2/conf-available/*.conf

# Install prequisites for PHP extensions
RUN apt-get update && apt-get install -y --no-install-recommends \
    libmcrypt-dev mysql-client libmagickwand-dev curl libcurl4-gnutls-dev librtmp-dev zip git

# Install various PHP extensions needed
RUN pecl install imagick \
    && docker-php-ext-enable imagick \
    && docker-php-ext-install pdo_mysql \
    && docker-php-ext-install mysqli \
    && docker-php-ext-install mbstring \
    && docker-php-ext-install xml \
    && docker-php-ext-install curl \
    && docker-php-ext-install gd \
    && docker-php-ext-install zip

# Install PHP Redis extension
RUN pecl install redis
RUN docker-php-ext-enable redis

# Install composer
COPY --from=composer:latest /usr/bin/composer /usr/bin/composer
````

The last line fails with:

````
#12 copy /src-0/composer usr/bin/composer
#12       digest: sha256:82163c5bd9e7b8f571c43996de7832ef1f4a35497610a0fb8c51bbb31a4bd0d2
#12         name: "copy /src-0/composer usr/bin/composer"
#12      started: 2018-06-21 09:10:06.424176447 +0200 CEST m=+214.181669191
#12 0.154 panic: failed to copy /src-0/composer to usr/bin/composer: failed to copy files: copy file range failed:                               operation not permitted
#12 0.154
#12 0.154 goroutine 1 [running]:
#12 0.154 main.main()
#12 0.154   /go/src/github.com/tonistiigi/copy/cmd/copy/main.go:57 +0x2b1
#12    completed: 2018-06-21 09:10:06.659891281 +0200 CEST m=+214.417384089
#12     duration: 235.714898ms
#12        error: "executor failed running [copy /src-0/composer usr/bin/composer]: exit code 2"
````

**Comment by nogoegst** [comment] 2018-06-21 10:44
```COPY --from=composer:latest /usr/bin/composer /usr/bin/composer```
@pixelspark, does it work with Docker?

**Comment by pixelspark** [comment] 2018-06-21 13:54
@nogoegst yes, same build works fine with Docker..

**Comment by nogoegst** [comment] 2018-06-21 14:41
@pixelspark I can't reproduce it. What `img` version are you using?

**Comment by pixelspark** [comment] 2018-06-21 15:13
I downloaded img from [here](https://github.com/genuinetools/img/releases/tag/v0.4.6).
````
img:
 version     : v0.4.6
 git hash    : 9c9f6f6
 go version  : go1.10.3
 go compiler : gc
 platform    : linux/amd64
````

Docker:

````
Client:
 Version:      18.03.1-ce
 API version:  1.37
 Go version:   go1.9.5
 Git commit:   9ee9f40
 Built:        Thu Apr 26 07:17:14 2018
 OS/Arch:      linux/amd64
 Experimental: false
 Orchestrator: swarm

Server:
 Engine:
  Version:      18.03.1-ce
  API version:  1.37 (minimum version 1.12)
  Go version:   go1.9.5
  Git commit:   9ee9f40
  Built:        Thu Apr 26 07:15:24 2018
  OS/Arch:      linux/amd64
  Experimental: false
````

Linux:

````
Linux m1 4.9.0-6-amd64 #1 SMP Debian 4.9.82-1+deb9u3 (2018-03-02) x86_64 GNU/Linux
````

**Comment by pixelspark** [comment] 2018-06-21 15:21
Minimal docker file that causes an error:

````
FROM php:7.0-apache
COPY --from=composer:latest /usr/bin/composer /usr/bin/compose
````

Outputs:
````
# ../img build -t test .
Building docker.io/library/test:latest
Setting up the rootfs... this may take a bit.
[+] Building 1.6s (6/6) FINISHED
 => local://dockerfile (testdocker)                                                                             0.0s
 => => transferring dockerfile: 223B                                                                            0.0s
 => local://context (.dockerignore)                                                                             0.0s
 => => transferring context: 02B                                                                                0.0s
 => docker-image://docker.io/library/composer:latest@sha256:e01cde665348338f5c77d48656e373f26771940ccf192c7e6d  0.2s
 => => resolve docker.io/library/composer:latest@sha256:e01cde665348338f5c77d48656e373f26771940ccf192c7e6d4eea  0.0s
 => => sha256:14614f6c0922d15c78b2a53c4737c3f6fe8aeb389b9e8476550a5d9174490ee3 3.46kB / 3.46kB                  0.0s
 => => sha256:f6ed00f048c74c2261c9dde19a880ce78760e312a7676f7a12c45cddf2a9c12d 92B / 92B                        0.0s
 => => sha256:1253fa17a201519712cf30bc2462187063bb901b076d24fc9c0ad0e2572eb0fc 1.25kB / 1.25kB                  0.0s
 => => sha256:adc947f2c77af2a6c25d2065a830a684deaaf08b7d75b7ac41abf70fb893330e 11.92kB / 11.92kB                0.0s
 => => sha256:19114b16b6a979206dfa16ac388dbad5db0c335f3bf4ea2fa01923b2e7bcf818 229.05kB / 229.05kB              0.0s
 => => sha256:e01cde665348338f5c77d48656e373f26771940ccf192c7e6d4eeaedb7672ab5 434B / 434B                      0.0s
 => => sha256:27352c60038283925f3392b22b37365ea58734b2d5500fe5cc83ab1b98efeae4 284B / 284B                      0.0s
 => => sha256:a9ef1dc975f614c830ce9cc0713c59fc69e63fbe587e39e086fe60262cf09b5d 26.20MB / 26.20MB                0.0s
 => => sha256:37eeb571555e5ae71167266500b40525256a631b61f4f80c28de8915fc268a74 17.22MB / 17.22MB                0.0s
 => => sha256:01ce3cad229c1194c8659d8569dfe280c51af2634b43f16c364c54391f2ce009 167B / 167B                      0.0s
 => => sha256:cdfaea5f3452c69e07ad7b0396a1fe6a3b604d0adfc3127d1be8f55c823ac913 498B / 498B                      0.0s
 => => sha256:83a4fb099be6464231b596b0318ded7889e08085ad856a38057cc2509b3c75c9 71.02kB / 71.02kB                0.0s
 => => sha256:bda19c3995f3412d10e3b94f23e015dd599e453165bf64eb1b07e4ce3ce1772c 2.17kB / 2.17kB                  0.0s
 => => sha256:b08b290290a2633974e68c5795e36f721f8d39522dc28e16fed884f88cf3246a 12.13MB / 12.13MB                0.0s
 => => sha256:ff3a5c916c92643ff77519ffa742d3ec61b7f591b6b7504599d95a4a41134e28 2.07MB / 2.07MB                  0.0s
 => => sha256:b9833b0afc68f3c69172f198b795184dd481f663e21b948642f06ca8b280eb94 1.27MB / 1.27MB                  0.0s
 => => sha256:773052884bd02f7a7bbb91a86dba4fffb9cc6912b91a0568e8c578f59e7806cd 472.21kB / 472.21kB              0.0s
 => => sha256:4def0c775c147666bbda1429cd45a381dcd1b70881fb2c31177a7a6718d564ec 536B / 536B                      0.0s
 => => unpacking docker.io/library/composer:latest@sha256:e01cde665348338f5c77d48656e373f26771940ccf192c7e6d4e  0.0s
 => docker-image://docker.io/tonistiigi/copy:v0.1.3@sha256:87c46e7b413cdd2c2702902b481b390ce263ac9d942253d366f  0.2s
 => => resolve docker.io/tonistiigi/copy:v0.1.3@sha256:87c46e7b413cdd2c2702902b481b390ce263ac9d942253d366f3b1a  0.0s
 => => sha256:b5fd220f9e38fc61daf5af13e8a98c18827822428bf6acab1bc1dc67586d6c1a 2.45kB / 2.45kB                  0.0s
 => => sha256:f5fd20edad0c69902cf702c6b080bcfac264c392f71871eccd39a5f171b01149 751.94kB / 751.94kB              0.0s
 => => sha256:58370f0d30e03a5cd4641c95b7e02d2983d1ebf3d6b34f7051d690b9b8512cb6 70.72kB / 70.72kB                0.0s
 => => sha256:ed81d31ad9fbd2898dd7b6f490978b3d20c9eb99eed30b509f03977e0096f238 98.68kB / 98.68kB                0.0s
 => => sha256:87c46e7b413cdd2c2702902b481b390ce263ac9d942253d366f3b1a3c16f96d6 1.36kB / 1.36kB                  0.0s
 => => sha256:8cd25ee4c3d612d46a5ca115a715a2a1482c5766428c3febb5835296e3e91a16 300.71kB / 300.71kB              0.0s
 => => sha256:7b75ca719cf195ac5ed9863efe1e677c4ed7a0b87db3e2f5daf895f9f84340d8 172.86kB / 172.86kB              0.0s
 => => unpacking docker.io/tonistiigi/copy:v0.1.3@sha256:87c46e7b413cdd2c2702902b481b390ce263ac9d942253d366f3b  0.0s
 => CACHED docker-image://docker.io/library/php:7.0-apache@sha256:42317bc2b120f2ca416ebe839a81cd8c545dca294481  0.0s
 => => resolve docker.io/library/php:7.0-apache@sha256:42317bc2b120f2ca416ebe839a81cd8c545dca294481d55ae64c023  0.0s
 => ERROR copy /src-0/composer usr/bin/composer                                                                 0.3s
------
 > copy /src-0/composer usr/bin/composer:
#6 0.207 panic: failed to copy /src-0/composer to usr/bin/composer: failed to copy files: copy file range failed: operation not permitted
#6 0.207
#6 0.207 goroutine 1 [running]:
#6 0.207 main.main()
#6 0.207        /go/src/github.com/tonistiigi/copy/cmd/copy/main.go:57 +0x2b1
------
failed to solve: executor failed running [copy /src-0/composer usr/bin/composer]: exit code 2
````

**Comment by pixelspark** [comment] 2018-06-21 15:34
Was also able to reproduce on another Debian 9.4 host. For some reason it doesn't work when running as non-root, it complains:

```` 
newgidmap: write to gid_map failed: Invalid argument
nsenter: failed to use newgidmap: No such file or directory
nsenter: failed to sync with parent: SYNC_USERMAP_ACK: got 255: No such file or directory
````

Then when I run it using `sudo` it shows the message as above (where I ran as root anyway).

**Comment by AkihiroSuda** [comment] 2018-06-25 03:13
@pixelspark `/etc/subgid` is not configured?

**Comment by pixelspark** [comment] 2018-06-26 01:12
@AkihiroSuda On the first server `/etc/subuid` and `/etc/subgid` exist and are filled. Anything in particular I can check?

**Comment by AkihiroSuda** [comment] 2018-06-26 02:59
Does `newuidmap`/`newgidmap` work with manual invocation?

**Comment by pixelspark** [comment] 2018-06-26 04:15
It does now on the first server (after doing `apt install uidmap`) but it still shows the same error...

````
 => ERROR copy /src-0/composer usr/bin/composer                            0.2s
------
 > copy /src-0/composer usr/bin/composer:
#6 0.110 panic: failed to copy /src-0/composer to usr/bin/composer: failed to copy files: copy file range failed: operation not permitted
#6 0.110 
#6 0.110 goroutine 1 [running]:
#6 0.110 main.main()
#6 0.110 	/go/src/github.com/tonistiigi/copy/cmd/copy/main.go:57 +0x2b1
------
failed to solve: executor failed running [copy /src-0/composer usr/bin/composer]: exit code 2
````

**Comment by pandrew** [comment] 2018-08-14 08:33
This is probably due to to containerd/go-runc  parser requires runc --version to include runc, commit and spec to be set. This means you cant use the release candidate v1.0.0-rc5 from https://github.com/opencontainers/runc/releases but you have to build the candidate yourself.

**Comment by oblique** [comment] 2018-09-01 11:48
The embedded `runc` binary has the problem. If I compiled runc by my own, even on the same commit that embedded runc is (i.e. b4e2ecb452d9ee4381137cc0a7e6715b96bed6de), I don't get this error.

Also as @pandrew mention, `containerd/go-runc` expects `commit:`, that's why `img` fallbacks to the embedded `runc`.

**Comment by oblique** [comment] 2018-12-06 22:17
Sorry for the delay, yes you can close it.

**Closed** 2018-12-07 03:05 UTC
Labels: bug
